Controllers/AlmoxarifadoController.cs
using Models;
using Models.Estoque;
using PortalMOB.Repositories.Interfaces;
using PowerOne.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Unity.Injection;

namespace PortalMOB.Controllers
{
    [Authorize]
    public class AlmoxarifadoController : Controller
    {
        private readonly IAlmoxarifadoRepository _almoxarifadoRepository;
        private readonly IEstoqueRepository _estoqueRepository;
        private readonly IDepositoRepository _depositoRepository;
        private readonly IConfiguracoesRepository _configuracoesRepository;
        private readonly ICentroCursoRepository _centroCustoRepository;
        public AlmoxarifadoController(
            IAlmoxarifadoRepository almoxarifadoRepository,
            IEstoqueRepository estoqueRepository,
            IDepositoRepository depositoRepository,
            ICentroCursoRepository centroCursoRepository,
            IConfiguracoesRepository configuracoesRepository
            )
        {
            _centroCustoRepository = centroCursoRepository;
            _configuracoesRepository = configuracoesRepository;
            _depositoRepository = depositoRepository;
            _estoqueRepository = estoqueRepository;
            _almoxarifadoRepository = almoxarifadoRepository;
        }

        #region Index / List
        public ActionResult Index(string dtInicio, string dtFim, string status, int tipo)
        {
            //Aprovado - tipo = 3
            //Em Curso - tipo = 4
            //Concluidos - tipo = 5
            Login login = (Login)Session["auth"];
            Autorizacoes autorizacoes = ((Login)Session["auth"]).Autorizacoes;

            if (
                autorizacoes.ReqEstoque == "N" &&
                autorizacoes.Grupo.ReqEstoque == "N"
               )
                return RedirectToAction("NaoAutorizado", "Home");

            List<RequerimentoEstoque> requerimentos = _almoxarifadoRepository.List(
                login, dtInicio, dtFim, status, tipo
            );
            TempData["tipo"] = tipo.ToString();
            TempData["requerimentos"] = requerimentos;
            return View();

        }
        #endregion

        #region details

        public ActionResult Details(int DocEntry)
        {
            Autorizacoes autorizacoes = ((Login)Session["auth"]).Autorizacoes;
            List<Deposito> deposito = new List<Deposito>();
            List<ItemEstoque> itens = new List<ItemEstoque>();
            if (
                         autorizacoes.ReqEstoque == "N" &&
                         autorizacoes.Grupo.ReqEstoque == "N"
                        )
                return RedirectToAction("NaoAutorizado", "Home");

            int[] dimensoesCtCusto = _configuracoesRepository.GetDimencoes();
            if (dimensoesCtCusto.Contains(1))
            {
                List<CentroCusto> centroCustos = _centroCustoRepository.List(1);
                TempData["ctCusto"] = centroCustos;
            }

            if (dimensoesCtCusto.Contains(2))
            {
                List<CentroCusto> centroCustos2 = _centroCustoRepository.List(2);
                TempData["ctCusto2"] = centroCustos2;
            }
            if (dimensoesCtCusto.Contains(3))
            {
                List<CentroCusto> centroCustos3 = _centroCustoRepository.List(3);
                TempData["ctCusto3"] = centroCustos3;
            }
            if (dimensoesCtCusto.Contains(4))
            {
                List<CentroCusto> centroCustos4 = _centroCustoRepository.List(4);
                TempData["ctCusto4"] = centroCustos4;
            }
            if (dimensoesCtCusto.Contains(5))
            {
                List<CentroCusto> centroCustos5 = _centroCustoRepository.List(5);
                TempData["ctCusto5"] = centroCustos5;
            }
            TempData["dimencoes"] = dimensoesCtCusto;



            TempData["dimencoes"] = dimensoesCtCusto;

            TempData["depositos"] = deposito;
            TempData["itens"] = itens;

            RequerimentoEstoque requerimento = _estoqueRepository.GetByKey(DocEntry);

            return View(requerimento);

        }

        #endregion

        #region Em curso / Entregue

        public ActionResult AtualizaReqAlmoxarifado(int DocEntry, string Tipo, string status)
        {
            //Aprovado - tipo = 3
            //Em Curso - tipo = 4
            //Concluidos - tipo = 5

            //O - Aberto
            //A - Aprovada
            //P - Em Curso
            //R - Aguardando Retirada
            //Y - Concluido
            //C - Cancelada
            RequerimentoEstoque requerimento = _estoqueRepository.GetByKey(DocEntry);
            string result = "";
            if (status == "C")
            {
                result = _almoxarifadoRepository.AttReq(requerimento.DocEntry, status);
            }
            else
            {
                if (Tipo == "5")
                {
                    result = _almoxarifadoRepository.FecharRequerimento(requerimento, (Login)Session["auth"], status);
                }
                else
                {
                    result = _almoxarifadoRepository.AttReq(requerimento.DocEntry, status);
                }
            }

            if (result != "Atualizado com sucesso!" && result != "Concluido com sucesso")
            {
                TempData["error"] = result;
            }
            else
            {
                TempData["success"] = $"Documento {DocEntry} ";
                TempData["success"] += result;
            }

            return RedirectToAction(nameof(Index), new { tipo = Tipo });
        }

        #endregion
    }
}

Views/Almoxarifado/index.cshtml
@{
    List<Models.Estoque.RequerimentoEstoque> requerimentos = (List<Models.Estoque.RequerimentoEstoque>)TempData["requerimentos"];
    Layout = "~/Views/Shared/_Layout.cshtml";

    string diretorio = ((PowerOne.Models.Login)Session["auth"]).Tema.Icon;
    string tipo = TempData["tipo"].ToString();
    if (String.IsNullOrEmpty(diretorio))
    {
        diretorio = "PRO";
    }
    int quant = 0;

}

<h1 class="col-12 text-center m-auto mb-4">
    Lista das Solicitações
    @if (tipo == "3")
    {
        @("Aprovadas".ToString())
    }
    else if (tipo == "4")
    {
        @("Em Curso".ToString())
    }
    else
    {
        @("Concluídas".ToString())
    }
</h1>

@if (TempData["Success"] != null)
{
    <div class="alert alert-success col-10 mx-auto my-2" role="alert">
        @TempData["Success"].ToString()
    </div>
}

@if (TempData["Error"] != null)
{
    <div class="alert alert-danger col-10 mx-auto" role="alert">
        @TempData["Error"].ToString()
    </div>
}

<div class="row mt-4">
    <div class="col-10 mx-auto p-0">
        <div class="card p-0">
            <div class="card-header">
                <form action="~/Almoxarifado/index">
                    <div class="row m-auto">
                        <input type="text" name="tipo" class="d-none" value="@tipo" />
                        <p class="mt-3">De:</p>
                        <div class="col m-2">
                            <input type="date" class="form-control" name="dtInicio" />
                        </div>
                        <p class="mt-3">Até:</p>
                        <div class="col m-2">
                            <input type="date" class="form-control col" name="dtFim" />
                        </div>

                        <div class="col m-2">
                            <input class="form-control" type='search' id='txt_searchall' placeholder='Digite..'>&nbsp;
                        </div>

                        <div class="col m-2">
                            <button type="submit" class="btn btn-block btn-success" name="name" value="">Pesquisar</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="card-body scroll max-height-500 p-0">
                <table class="col-12 table table-striped mx-auto" id="tabelaIndex">
                    <thead class="text-white">
                        <tr>
                            <th>
                                Visualizar
                            </th>
                            @if (tipo != "5")
                            {
                                <th>
                                    Aprovar
                                </th>
                            }
                            else
                            {
                                <th>
                                    Concluir
                                </th>
                            }
                            <th>
                                Nº Documento
                            </th>
                            <th>
                                Status
                            </th>
                            <th>
                                Solicitante
                            </th>
                            <th>
                                Data
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @try
                        {
                            quant = requerimentos.Count();
                        }
                        catch (Exception)
                        {
                            <tr>
                                <td colspan="6">
                                    <p> Sem registros </p>
                                </td>
                            </tr>
                        }
                        @if (quant == 0)
                        {
                        }
                        else
                        {
                            foreach (var item in requerimentos)
                            {
                                <tr>
                                    <td>
                                        @Html.ActionLink("arrow_forward", "Details", "Almoxarifado", new { DocEntry = item.DocEntry }, new { @class = "btn btn-outline-dark material-icons" })
                                    </td>
                                    <td>
                                        @if (item.U_P1_STATUS != "Concluído")
                                        {
                                            <button type="button" class="btn btn-success material-icons" data-toggle="modal" data-target="#modalList@(item.DocEntry)">check</button>

                                        }
                                        else
                                        {
                                            <button type="button" class="btn btn-secondary material-icons" disabled>check</button>
                                        }
                                    </td>
                                    <td>
                                        @item.DocNum
                                    </td>
                                    <td>
                                        @item.U_P1_STATUS
                                    </td>
                                    <td>
                                        @item.U_P1_Owner.Replace(".", " ")
                                    </td>
                                    <td>
                                        @DateTime.Parse(item.U_P1_DTLANC).ToString("dd/MM/yyyy")
                                    </td>
                                </tr>
                                <form action="~/Almoxarifado/AtualizaReqAlmoxarifado?Tipo=@tipo" method="POST">
                                    <input type="number" class="d-none" name="DocEntry" value="@item.DocEntry" />
                                    <div class="modal fade" id="modalList@(item.DocEntry)" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Prosseguir Solicitação para proxima etapa</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    Deseja seguir a solicitação @item.DocEntry para a etapa
                                                    @if (tipo == "5")
                                                    {
                                                        @(("Aprovar").ToString());
                                                    }
                                                    else if (tipo == "4")
                                                    {
                                                        @(("Concluído").ToString());
                                                    }
                                                    else
                                                    {
                                                        @(("Em Curso").ToString());
                                                    }
                                                    ,a solicitação foi criada por @item.U_P1_Owner.Replace(".", " ") em @DateTime.Parse(item.U_P1_DTLANC).ToString("dd/MM/yyyy").
                                                </div>
                                                <div class="modal-footer">
                                                    @*//O - Aberto
                                                        //A - Aprovada
                                                        //P - Em Curso
                                                        //R - Aguardando Retirada
                                                        //Y - Concluido
                                                        //C - Cancelada*@
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Voltar</button>
                                                    @if (tipo == "5")
                                                    {
                                                        if (item.U_P1_STATUS == "Aguardando Retirada")
                                                        {
                                                            @Html.ActionLink("Concluir Solicitação", "AtualizaReqAlmoxarifado", "Almoxarifado", new { DocEntry = item.DocEntry, Tipo = tipo, Status = "Y" }, new { @class = "btn btn-primary " })
                                                        }
                                                    }
                                                    else if (tipo == "3")
                                                    {
                                                        @Html.ActionLink("Prosseguir para Em Curso", "AtualizaReqAlmoxarifado", "Almoxarifado", new { DocEntry = item.DocEntry, Tipo = tipo, Status = "P" }, new { @class = "btn btn-primary " })
                                                    }
                                                    else if (tipo == "4")
                                                    {
                                                        @Html.ActionLink("Prosseguir para Aguardando Retirada", "AtualizaReqAlmoxarifado", "Almoxarifado", new { DocEntry = item.DocEntry, Tipo = tipo, Status = "R" }, new { @class = "btn btn-primary " })
                                                    }

                                                    @Html.ActionLink("Cancelar Documento", "AtualizaReqAlmoxarifado", "Almoxarifado", new { DocEntry = item.DocEntry, Tipo = tipo, Status = "C" }, new { @class = "btn btn-outline-danger " })

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>



@section scripts{

    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap-dataTable.css">
    <script>
        $(document).ready(function () {
            $("#txt_searchall").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("tbody tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });


        $(document).ready(function () {
            $('#tabelaIndex').DataTable({
                "columnDefs": [{ "targets": [0], "orderable": false }],
                "order": [3, 'asc'],
                "info": false,
                "paging": false,
                "searching": false,
                "language": {
                    "lengthMenu": "Display _MENU_ records per page",
                    "zeroRecords": "Nada encontrado",
                    "info": "Showing page _PAGE_ of _PAGES_",
                    "infoEmpty": "Nenhum dado encontrado",
                    "infoFiltered": "(filtered from _MAX_ total records)"
                }
            });
        });

    </script>
}