Controllers/AprovacaoController.cs
using Models.Estoque;
using PortalMOB.Repositories.Interfaces;
using PowerOne.Models;
using PowerOne.Repository;
using System.Collections.Generic;
using System.Web.Mvc;

namespace PortalMOB.Controllers
{
    [Authorize]
    public class AprovacaoController : Controller
    {
        #region Dependencias
        private readonly IAprovacaoRepository _aprovacaoRepository;
        public AprovacaoController(
            IAprovacaoRepository aprovacaoRepository
        )
        {
            _aprovacaoRepository = aprovacaoRepository;
        }

        #endregion

        #region Index
        public ActionResult Index(string DataInicio, string DataFim, string Status)
        {
            TempData["requerimentos"] = _aprovacaoRepository.searchList(DataInicio, DataFim, Status);
            
            return View();
        }
        #endregion

        #region Aprovar
        public ActionResult Aprovar(string DocEntry)
        {
            string resul = null;

            resul = _aprovacaoRepository.aprovaReq(DocEntry, (Login)Session["auth"]);

            if (resul != "Atualizado com sucesso!")
            {
                TempData["error"] = resul;
            }
            else
            {
                TempData["success"] = resul;
            }

            return RedirectToAction(nameof(Index));
        }
        #endregion

        #region Fechar

        public ActionResult Fechar(string DocEntry)
        {

            string result = null;
            result = _aprovacaoRepository.fecharReq(DocEntry);
            return RedirectToAction(nameof(Index));

        }

        #endregion
    }
}

Controllers/EstoqueController.cs
using PortalMOB.Repositories.Interfaces;
using System.Web.Mvc;
using PowerOne.Controllers;
using PowerOne.Models;
using Models.Estoque;
using System.Collections.Generic;
using Models;
using PortalMOB.Models;
using Model.Estoque;
using System.Linq;
using System.Threading;
using System.Globalization;

namespace PortalMOB.Controllers
{
    [Authorize]
    public class EstoqueController : Controller
    {        
        #region Instancing Repositories 
        private readonly IEstoqueRepository _estoqueRepository;
        private readonly IConfiguracoesRepository _configuracoesRepository;
        private readonly IItemEstoqueRepository _itemEstoqueRepository;
        private readonly IFiliaisRepository _filiaisRepository;
        private readonly IDepositoRepository _depositoRepository;
        private readonly ICentroCursoRepository _centroCustoRepository;

        public EstoqueController(
            IEstoqueRepository estoqueRepository,
            IConfiguracoesRepository configuracoesRepository,
            IItemEstoqueRepository ItemEstoqueRepository,
            IFiliaisRepository filiaisRepository,
            IDepositoRepository depositoRepository,
            ICentroCursoRepository centroCustoRepository
            )
        {
            _depositoRepository = depositoRepository;
            _estoqueRepository = estoqueRepository;
            _configuracoesRepository = configuracoesRepository;
            _itemEstoqueRepository = ItemEstoqueRepository;
            _filiaisRepository = filiaisRepository;
            _centroCustoRepository = centroCustoRepository;
        }
        #endregion

        #region Index / List
        public ActionResult Index(string dtInicio, string dtFim, string status, string tipo)
        {
            Login login = (Login)Session["auth"];
            Autorizacoes autorizacoes = ((Login)Session["auth"]).Autorizacoes;

            if (autorizacoes.ReqEstoque == "N" && autorizacoes.Grupo.ReqEstoque == "N")
                return RedirectToAction("NaoAutorizado", "Home");

            List<RequerimentoEstoque> requerimentos = _estoqueRepository.List(
                login, dtInicio, dtFim, status, tipo
            );

            TempData["requerimentos"] = requerimentos;
            TempData["tipo"] = tipo;

            return View(requerimentos);
        }
        #endregion

        #region Details / GetByKey e ListarLinhas
        public ActionResult Details(int DocEntry, int Filial)
        {
            Thread.CurrentThread.CurrentCulture = new CultureInfo("pt-br", true);

            Autorizacoes autorizacoes = ((Login)Session["auth"]).Autorizacoes;

            if (autorizacoes.ReqEstoque == "N" && autorizacoes.Grupo.ReqEstoque == "N")
                return RedirectToAction("NaoAutorizado", "Home");

            List<Deposito> deposito = _depositoRepository.List(Filial);
            TempData["depositos"] = deposito;

            List<ItemEstoque> itens = _itemEstoqueRepository.List();
            TempData["itens"] = itens;

            int[] dimensoesCtCusto = _configuracoesRepository.GetDimencoes();
            TempData["dimencoes"] = dimensoesCtCusto;

            if (dimensoesCtCusto.Contains(1))
                TempData["ctCusto"] = _centroCustoRepository.List(1);
            if (dimensoesCtCusto.Contains(2))
                TempData["ctCusto2"] = _centroCustoRepository.List(2);
            if (dimensoesCtCusto.Contains(3))
                TempData["ctCusto3"] = _centroCustoRepository.List(3);
            if (dimensoesCtCusto.Contains(4))
                TempData["ctCusto4"] = _centroCustoRepository.List(4);
            if (dimensoesCtCusto.Contains(5))
                TempData["ctCusto5"] = _centroCustoRepository.List(5);                                  

            RequerimentoEstoque solicitacao = _estoqueRepository.GetByKey(DocEntry);

            return View(solicitacao);
        }
        #endregion

        #region Edit/Add Line

        public ActionResult Edit(RequerimentoEstoqueLinhas linha, int tipo, int filial)
        {
            if (string.IsNullOrEmpty(linha.U_P1_ItemCode) || string.IsNullOrEmpty(linha.U_P1_Quantity) || string.IsNullOrEmpty(linha.U_P1_WhsCode) )
            {
                TempData["error"] = "Para editar o documento, todos os campos devem ser preenchidos";
            }
            else
            {
                linha.U_P1_Quantity = linha.U_P1_Quantity.Replace(",", ".");
                string result = null;
                result = _estoqueRepository.EditAdd(linha, tipo);

                if (result != "Atualizado com sucesso")
                {
                    TempData["success"] = result;
                } else
                {
                    TempData["error"] = result;
                }
            }


            return RedirectToAction("Details", new {DocEntry = linha.DocEntry, Filial = filial});
        }
        #endregion

        #region Create / Create
        public ActionResult Create()
        {
            Login login = (Login)Session["auth"];
            //Autorizacoes autorizacoes = ((Login)Session["auth"]).Autorizacoes;
            //if (
            //    autorizacoes.CriarReqEstoque == "N" &&
            //    autorizacoes.Grupo.CriarReqEstoque == "N"
            //   )
            //    return RedirectToAction("NaoAutorizado", "Home");

            ConfDocumento configs = _configuracoesRepository.GetConfigurationsOfDocuments();
            TempData["config"] = configs;

            List<ItemEstoque> itens = _itemEstoqueRepository.List();
            List<Filiais> filiais = _filiaisRepository.List();
            int[] dimensoesCtCusto = _configuracoesRepository.GetDimencoes();
            List<Projetos> projetos = _estoqueRepository.getProjeto();


            if (dimensoesCtCusto.Contains(1))
            {
                List<CentroCusto> centroCustos = _centroCustoRepository.List(1);
                TempData["ctCusto"] = centroCustos;
            }

            if (dimensoesCtCusto.Contains(2))
            {
                List<CentroCusto> centroCustos2 = _centroCustoRepository.List(2);
                TempData["ctCusto2"] = centroCustos2;
            }
            if (dimensoesCtCusto.Contains(3))
            {
                List<CentroCusto> centroCustos3 = _centroCustoRepository.List(3);
                TempData["ctCusto3"] = centroCustos3;
            }
            if (dimensoesCtCusto.Contains(4))
            {
                List<CentroCusto> centroCustos4 = _centroCustoRepository.List(4);
                TempData["ctCusto4"] = centroCustos4;
            }
            if (dimensoesCtCusto.Contains(5))
            {
                List<CentroCusto> centroCustos5 = _centroCustoRepository.List(5);
                TempData["ctCusto5"] = centroCustos5;
            }

            TempData["projetos"] = projetos;
            TempData["dimencoes"] = dimensoesCtCusto;
            TempData["ItensEstoque"] = itens;
            TempData["filiais"] = filiais;



            return View();
        }
        #endregion

        #region Add Estoque
        [HttpPost]
        public JsonResult Add(RequerimentoEstoque ReqEstoque)
        {
            var resultado = new { msg = "", type = "" };

            //int[] dimencoes = _configuracoesRepository.GetDimencoes();

            Resultado resul = _estoqueRepository.AddReq(ReqEstoque,(Login)Session["auth"]);

            if (resul.Msg != "error")
            {
                resultado = new
                {
                    msg = "Solicitação de Material e Equipamento Adicionada com Sucesso",
                    type = "success"
                };
            }
            else
            {
                resultado = new
                {
                    msg = resul.Msg,
                    type = "error"
                };
            }
            return Json(resultado, JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

Views/Aprovacao/Index.cshtml
@{
    List<Models.Estoque.RequerimentoEstoque> requerimentos = (List<Models.Estoque.RequerimentoEstoque>)TempData["requerimentos"];
    Layout = "~/Views/Shared/_Layout.cshtml";
    int contagem = 0;
}
<div class="row m-auto">
    <h1 class="mb-2 m-auto">Lista das Solicitações de Materiais sob Aprovação</h1>
</div>
<hr />
@if (TempData["Success"] != null)
{
    <div class="alert alert-success col-10 mx-auto my-2" role="alert">
        @TempData["Success"].ToString()
    </div>
}

@if (TempData["Error"] != null)
{
    <div class="alert alert-danger col-10 mx-auto" role="alert">
        @TempData["Error"].ToString()
    </div>
}

<div class="card col mx-auto bg-light p-0">
    <div class="card-header">
        <p>Data de Lançamento</p>
        <form action="~/Aprovacao/Index">
            <div class="row">
                <div class="col-md-3 form-group col-sm-12">
                    <label>De:</label>
                    <input type="date" class="form-control" name="dtInicio" />
                </div>
                <div class="col-md-3 form-group col-sm-12">
                    <label>Até:</label>
                    <input type="date" class="form-control" name="dtFim" />
                </div>
                <div class="col-md-3 form-group col-sm-12">
                    <label>Pesquisar:</label>
                    <input class="form-control" type='search' id='txt_searchall' placeholder='Digite..'>&nbsp;
                </div>
                <div class="col-md-3 form-group col-sm-12">
                    <div class="row">
                        <label class="col-12"><br /></label>
                        <button type="submit" class="btn btn-outline-success col-md-12"><i class="material-icons">search</i></button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="card-body p-0 scroll max-height-500">
        <table class="table table-striped col-md-12 m-auto">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Visualizar</th>
                    <th scope="col">Ação</th>
                    <th scope="col">Status</th>
                    <th scope="col">Data da Solicitação</th>
                    <th scope="col">Requisitante</th>
                </tr>
            </thead>
            <tbody>
                @try
                {
                    contagem = requerimentos.Count();
                }
                catch (Exception)
                {
                    <tr>
                        <td colspan="6">
                            <p> Sem registros </p>
                        </td>
                    </tr>
                }
                @if (contagem == 0)
                {

                }
                else
                {
                    foreach (var item in requerimentos)
                    {
                        <tr>
                            <td>
                                @Html.ActionLink("arrow_forward", "Details", "Estoque", new { DocEntry = item.DocEntry, Filial = item.U_P1_IDFILIAL }, new { @class = "btn btn-outline-dark material-icons" })
                            </td>
                            <td>
                                <button type="submit" class="material-icons btn btn-success" data-toggle="modal" data-target="#exampleModal@(item.DocEntry)">
                                    thumb_up
                                </button>
                            </td>
                            <td>@(item.U_P1_STATUS)</td>
                            <td>@(DateTime.Parse(item.U_P1_DTLANC).ToString("dd/MM/yyyy"))</td>
                            <td>@(item.U_P1_Owner)</td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>


@foreach (var item in requerimentos)
{
    <form action="~/Aprovacao/Aprovar" method="post">
        <input type="text" class="d-none" name="DocEntry" value="@item.DocEntry" />
        <div class="modal fade" id="exampleModal@(item.DocEntry)" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Aprovar o seguinte documento</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Deseja Aprovar a solciitação numero @(item.DocEntry), criada por @(item.U_P1_Owner.Replace("."," ")) em @(DateTime.Parse(item.U_P1_DTLANC).ToString("dd/MM/yyyy"))
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-success">Aprovar</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
}