Models/Autorizacoes.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PowerOne.Models
{
    public class Autorizacoes
    {
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string UserLastName { get; set; }
        public string ReqEstoque { get; set; }
        public string CriarReqEstoque { get; set; }
        public string IdGrupo { get; set; }
        public AutorizacoesGrupo Grupo { get; set; }
        public string Tipo { get; set; }
        public string Autorizador { get; set; }
        public string Almoxarifado { get; set; }
    }

   
}

Models/Tema.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PowerOne.Models
{
    public class Tema
    {
        public string UserId { get; set; }

        public string Color { get; set; }

        public string Icon { get; set; }
    }
}

Controllers/ConfiguracoesController.cs
using PowerOne.Models;
using PowerOne.Repository;
using PowerOne.Util;
using System;
using System.Collections.Generic;
using System.IO;
using System.Web;
using System.Web.Mvc;
using System.Web.Hosting;
using PortalMOB.Repositories.Interfaces;
using PortalMOB.Models;
using PortalMOB.Repositories;

namespace PowerOne.Controllers
{
    [Authorize]
    public class ConfiguracoesController : Controller
    {
        #region Intancing Repositories 
        private readonly IConfiguracoesRepository _configuracoesRepository;
        private readonly IAutorizacoesRepository _autorizacoesRepository;
        private readonly IFiliaisRepository _filiaisRepository;
        private readonly IDepositoRepository _depositoRepository;

        public ConfiguracoesController(
            IConfiguracoesRepository configuracoesRepository,
            IAutorizacoesRepository autorizacoesRepository,
            IFiliaisRepository filiaisRepository,
            IDepositoRepository depositoRepository
        )
        {
            _configuracoesRepository = configuracoesRepository;
            _autorizacoesRepository = autorizacoesRepository;
            _filiaisRepository = filiaisRepository;
            _depositoRepository = depositoRepository;
        }
        #endregion

        #region Configurar Email
        public ActionResult Email()
        {
            //if (((Login)Session["auth"]).Autorizacoes.Tipo != "Adm")
            //{
            //    return RedirectToAction("NaoAutorizado", "Home");
            //}

            ConfiguracoesEmail configuracoesEmail = _configuracoesRepository.GetConfiguracoesEmail();

            return View(configuracoesEmail);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Email(ConfiguracoesEmail configEmail)
        {
            if (!ModelState.IsValid)
            {
                return View(configEmail);
            }

            string msg = _configuracoesRepository.configuraremail(configEmail);

            if (msg != null)
            {
                TempData["Error"] = msg;
                Log.Gravar((string)TempData["Error"], Log.TipoLog.Erro);
            }
            else
            {
                TempData["Success"] = "Email Configurado com Sucesso!";
            }

            return View();
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Anexo(ConfiguracoesEmail confAnexo)
        //{
        //    string msg = _configuracoesService.ConfiguraAnexo(confAnexo);

        //    if (msg != null)
        //    {
        //        TempData["Error"] = msg;
        //        Log.Gravar((string)TempData["Error"], Log.TipoLog.Erro);
        //    }
        //    else
        //    {
        //        TempData["Success"] = "Anexos do Email Configurados com Sucesso!";
        //    }

        //    return RedirectToAction(nameof(Email));
        //}
        #endregion

        #region Temas
        public ActionResult Temas()
        {
            return View();
        }

        #endregion

        #region Autorizações
        public ActionResult Autorizacoes()
        {
            Autorizacoes autorizacoes = ((Login)Session["auth"]).Autorizacoes;

            //if (autorizacoes.Tipo != "Adm")
            //    return RedirectToAction("NaoAutorizado", "Home");

            TempData["autorizacoes"] = _autorizacoesRepository.List();
            TempData["autorizacoesGrupo"] = _autorizacoesRepository.ListGrupo();

            return View();
        }

        [HttpPost]
        public ActionResult Autorizacoes(Autorizacoes autorizacoes)
        {
            Login login = (Login)Session["auth"];

            string msg = null;

            msg = _autorizacoesRepository.Update(autorizacoes);

            if (msg != null)
            {
                TempData["Error"] = msg;
                Log.Gravar((string)TempData["Error"], Log.TipoLog.Erro);
            }
            else
            {
                TempData["Success"] = $"Autorizações atualizadas com sucesso.";
                ((Login)Session["auth"]).Autorizacoes = _autorizacoesRepository.PegarAutorizacoes(login.UserId.ToString());
                ((Login)Session["auth"]).Autorizacoes.Grupo = _autorizacoesRepository.PegarGrupoAutorizacoes(login.Autorizacoes.IdGrupo);
            }

            return RedirectToAction(nameof(Autorizacoes));
        }
        #endregion

        #region Configurações de Documentos
        public ActionResult DocConfig()
        {
            TempData["Dimensoes"] = _configuracoesRepository.GetDimencoes();
            TempData["filiais"] = _filiaisRepository.List();
            TempData["Configs"] = _configuracoesRepository.GetConfigurationsOfDocuments();

            return View();
        }
        #endregion





        #region Trocar Icones
        [HttpPost]
        public ActionResult ChangeIcons(string icon)
        {
            Login login = (Login)Session["auth"];

            if (icon != null)
            {
                Resultado response = _configuracoesRepository.ConfigurarTema(login.Id.ToString(), null, icon);

                if (response.Msg != null)
                {
                    TempData["Error"] = response.Msg;
                }
                else
                {
                    ((Login)Session["auth"]).Tema = _configuracoesRepository.GetTema(login.Id.ToString());
                    TempData["Success"] = "icones alterados com sucesso!";
                }
            }
            else
            {
                TempData["Error"] = "Selecione um icone!";
            }

            return RedirectToAction(nameof(Temas));
        }
        #endregion

        #region Upload de Logo
        //[HttpPost]
        //public ActionResult UploadLogo(HttpPostedFileBase logo)
        //{
        //    string msg = null;
        //    try
        //    {
        //        if (logo != null)
        //        {
        //            string path = Path.Combine(Server.MapPath("~/Content/img"), "logo-company.png");
        //            logo.SaveAs(path);
        //        }
        //    }
        //    catch (Exception e)
        //    {
        //        msg = e.Message;
        //    }

        //    if (msg != null)
        //    {
        //        TempData["Error"] = msg;
        //        Log.Gravar((string)TempData["Error"], Log.TipoLog.Erro);
        //    }
        //    else
        //    {
        //        TempData["Success"] = "Logo do site alterada com sucesso!";
        //    }

        //    return RedirectToAction(nameof(Temas));
        //}
        #endregion

        #region Configurar Cor do Menu
        [HttpPost]
        public ActionResult TrocarCorMenu(string color)
        {
            Resultado resultado = new Resultado();
            if (color != null)
            {
                resultado = _configuracoesRepository.ConfigurarTema(((Models.Login)Session["auth"]).UserId.ToString(), color, null);

                if (resultado.Msg != null)
                {
                    TempData["Error"] = resultado.Msg;
                    Log.Gravar((string)TempData["Error"], Log.TipoLog.Erro);
                }
                else
                {
                    ((Models.Login)Session["auth"]).Tema = _configuracoesRepository.GetTema(((Models.Login)Session["auth"]).UserId.ToString());
                    TempData["Success"] = "Cor do menu alterado com sucesso!";
                }
            }
            else
            {
                TempData["Error"] = "Selecione uma cor!";
                Log.Gravar((string)TempData["Error"], Log.TipoLog.Erro);
            }

            return RedirectToAction(nameof(Temas));
        }
        #endregion





        #region Autorizacoes para Grupo
        public ActionResult AtualizarAutorizacoesGrupo(AutorizacoesGrupo autorizacoes)
        {
            string msg = _autorizacoesRepository.AtualizarAutorizacoesGrupos(autorizacoes);

            if (msg != null)
            {
                TempData["Error"] = msg;
            }
            else
            {
                TempData["Success"] = "Autorização atualizada com sucesso!";
                ((Login)Session["auth"]).Autorizacoes = _autorizacoesRepository.PegarAutorizacoes(((Login)Session["auth"]).Id.ToString());
                ((Login)Session["auth"]).Autorizacoes.Grupo = _autorizacoesRepository.PegarGrupoAutorizacoes(((Login)Session["auth"]).Id.ToString());
            }

            return RedirectToAction("Autorizacoes");
        }
        #endregion

        #region Adicionar Grupo
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult AddGroup(string GroupName)
        //{
        //    string msg = null;

        //    msg = _autorizacoesService.CriarGrupos(GroupName, GroupName);

        //    if (msg != null)
        //    {
        //        TempData["Error"] = msg;
        //    }
        //    else
        //    {
        //        TempData["Success"] = "Grupo Criado com sucesso.";
        //        ((Login)Session["auth"]).Autorizacoes = _autorizacoesService.PegarAutorizacoes(((Login)Session["auth"]).Id.ToString());
        //        ((Login)Session["auth"]).Autorizacoes.Grupo = _autorizacoesService.PegarGrupoAutorizacoes(((Login)Session["auth"]).Autorizacoes);
        //    }

        //    return RedirectToAction(nameof(Autorizacoes));
        //}
        #endregion

        #region Adicionar/Atualizar o grupo de um usuário
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AtualizarGrupoUsuario(string idUser, string idGrupo)
        {
            string msg = null;
            if (String.IsNullOrEmpty(idGrupo))
            {
                msg = "Selecione um grupo.";
            }
            else
            {
                msg = _autorizacoesRepository.AtualizarGrupoDoUsuario(idUser, idGrupo);
            }

            if (msg != null)
            {

Views/Configuracoes/Email.cshtml
@model PowerOne.Models.ConfiguracoesEmail
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1 class="col-12 text-center">Configurar Email</h1>
<hr />

@if (TempData["Success"] != null)
{

    <div class="alert alert-success" role="alert">
        @TempData["Success"].ToString()
    </div>
}
else if (TempData["Error"] != null)
{
    <div class="alert alert-danger" role="alert">
        @TempData["Error"].ToString()
    </div>
}

<div class="card col-md-7 m-auto shadow p-5 mb-5 bg-light rounded">

    <div class="card-header">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item" role="presentation">
                <a class="nav-link active" id="email-tab" data-toggle="tab" href="#email" role="tab" aria-controls="email" aria-selected="true">Configurações de Email</a>
            </li>
          
        </ul>
    </div>

    <div class="tab-content card-body" id="ContentConfigEmail">

        <div class="tab-pane fade show active" id="email" role="tabpanel" aria-labelledby="email-tab">
            <form class="row" method="post">
                @Html.AntiForgeryToken()
                <div class="form-group col-md-6 p-2">
                    @Html.DisplayNameFor(model => Model.Email)
                    @Html.TextBoxFor(model => Model.Email, null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => Model.Email, String.Empty, new { @class = "text-danger" })
                </div>
                <div class="form-group col-md-6 p-2">
                    @Html.DisplayNameFor(model => Model.Senha)
                    @Html.TextBoxFor(model => Model.Senha, null, new { @class = "form-control", Type = "password" })
                    @Html.ValidationMessageFor(model => Model.Senha, String.Empty, new { @class = "text-danger" })
                </div>
                <div class="form-group col-md-6 p-2">
                    @Html.DisplayNameFor(model => Model.Servidor)
                    @Html.TextBoxFor(model => Model.Servidor, null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => Model.Servidor, String.Empty, new { @class = "text-danger" })
                </div>
                <div class="form-group col-md-6 p-2">
                    @Html.DisplayNameFor(model => Model.Porta)
                    @Html.TextBoxFor(model => Model.Porta, null, new { @class = "form-control", Type = "number" })
                    @Html.ValidationMessageFor(model => Model.Porta, String.Empty, new { @class = "text-danger" })
                </div>
                @*<div class="form-group col-md-12 p-2">
                        @Html.DisplayNameFor(model => Model.Servico)
                        @Html.TextBoxFor(model => Model.Servico, null, new { @class = "form-control" })
                    </div>*@
                <div class="form-group col-md-8 mx-auto row">
                    <div class="col-md-6">
                        <div class="row p-2">
                            <button class="btn btn-success col-md-12" type="submit">Salvar</button>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="row p-2">
                            @Html.ActionLink("Voltar", "Configuracoes", "Home", null, new { @class = "btn btn-outline-primary col-md-12" })
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

Views/Configuracoes/Temas.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    PowerOne.Models.Autorizacoes autorizacoes = ((PowerOne.Models.Login)Session["auth"]).Autorizacoes;

    PowerOne.Models.Login User = ((PowerOne.Models.Login)Session["auth"]);
    string color = null;
    if (User.Tema != null)
    {
        if (User.Tema.Color != null)
        {
            color = User.Tema.Color;
        }
    }
    string icon = null;
    if (User.Tema != null)
    {
        if (User.Tema.Icon != null)
        {
            icon = User.Tema.Icon;
        }
    }
}

<h1 class="text-center p-5">Temas</h1>

@if (TempData["Success"] != null)
{
    <div class="alert alert-success col-10 mx-auto my-2" role="alert">
        @TempData["Success"].ToString()
    </div>

    <div class="alert alert-warning col-10 mx-auto my-2" role="alert">
        <strong>AVISO:</strong> Se o tema não atualizar, limpe o cache do navegador e faça o login novamente.
    </div>
}

@if (TempData["Error"] != null)
{
    <div class="alert alert-danger col-10 mx-auto" role="alert">
        @TempData["Error"].ToString()
    </div>
}

<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
        <a class="nav-link active" id="menuLateral-tab" data-toggle="tab" href="#MenuLateral" role="tab" aria-controls="Menu Lateral" aria-selected="true">Menu Lateral</a>
    </li>
    @if (autorizacoes.Tipo == "Adm")
    {
        <li class="nav-item" role="presentation">
            <a class="nav-link" id="logo-tab" data-toggle="tab" href="#logo" role="tab" aria-controls="logo" aria-selected="false">Logo</a>
        </li>
    }
    <li class="nav-item" role="presentation">
        <a class="nav-link" id="icone-tab" data-toggle="tab" href="#icone" role="tab" aria-controls="icone" aria-selected="false">Ícones</a>
    </li>
</ul>

<div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active p-5" id="MenuLateral" role="tabpanel" aria-labelledby="menuLateral-tab">
        <div class="row">
            <form class="col-md-10 mx-auto" action="~/Configuracoes/TrocarCorMenu" method="post">
                <div class="row">
                    <div class="col-md-3">
                        <div>
                            <label for="dark" class="col-md-12 p-5 text-white text-center rounded" style="background-color: #343a40;"></label>
                            Preto:
                            @if (color == "BLACK")
                            {
                                <input type="radio" name="color" id="dark" value="BLACK" checked />
                            }
                            else
                            {
                                <input type="radio" name="color" id="dark" value="BLACK" />
                            }

                        </div>
                    </div>

                    <div class="col-md-3">
                        <div>
                            <label for="red" class="col-md-12 p-5 text-dark text-center rounded" style="background-color: #DC5B5B;">
                            </label>
                            Vermelho:
                            @if (color == "RED")
                            {
                                <input type="radio" name="color" id="red" value="RED" checked />
                            }
                            else
                            {
                                <input type="radio" name="color" id="red" value="RED" />
                            }
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div>
                            <label for="blue" class="col-md-12 p-5 text-dark text-center rounded" style="background-color: #44ABD8;">
                            </label>
                            Azul:
                            @if (color == "BLUE")
                            {
                                <input type="radio" name="color" id="blue" value="BLUE" checked />
                            }
                            else
                            {
                                <input type="radio" name="color" id="blue" value="BLUE" />
                            }
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div>
                            <label for="green" class="col-md-12 p-5 text-dark text-center rounded" style="background-color: #50C895;">
                            </label>
                            Verde:
                            @if (color == "GREEN")
                            {
                                <input type="radio" name="color" id="green" value="GREEN" checked />
                            }
                            else
                            {
                                <input type="radio" name="color" id="green" value="GREEN" />
                            }
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div>
                            <label for="dark-green" class="col-md-12 p-5 text-white text-center rounded" style="background-color: #32855D;">
                            </label>
                            Verde Escuro:
                            @if (color == "DARKGREEN")
                            {
                                <input type="radio" name="color" id="dark-green" value="DARKGREEN" checked />
                            }
                            else
                            {
                                <input type="radio" name="color" id="dark-green" value="DARKGREEN" />
                            }
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div>
                            <label for="orange" class="col-md-12 p-5 text-white text-center rounded" style="background-color: #d67604;">
                            </label>
                            Laranja:
                            @if (color == "ORANGE")
                            {
                                <input type="radio" name="color" id="orange" value="ORANGE" checked />
                            }
                            else
                            {
                                <input type="radio" name="color" id="orange" value="ORANGE" />
                            }
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div>
                            <label for="yellow" class="col-md-12 p-5 text-dark text-center rounded" style="background-color: #ffc107;">
                            </label>
                            Amarelo:
                            @if (color == "YELLOW")
                            {
                                <input type="radio" name="color" id="yellow" value="YELLOW" checked />
                            }
                            else
                            {
                                <input type="radio" name="color" id="yellow" value="YELLOW" />
                            }
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div>
                            <label for="purple" class="col-md-12 p-5 text-dark text-center rounded" style="background-color: #AA59C7;">
                            </label>
                            Roxo:
                            @if (color == "PURPLE")
                            {
                                <input type="radio" name="color" id="purple" value="PURPLE" checked />
                            }
                            else
                            {
                                <input type="radio" name="color" id="purple" value="PURPLE" />
                            }
                        </div>
                    </div>


                    <div class="col-md-12 m-auto p-5 d-flex justify-content-center">
                        <div class="col-md-3">
                            <div class="row p-2">
                                <button type="submit" class="btn btn-success col-md-12">Salvar</button>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="row p-2">
                                @Html.ActionLink("Voltar", "Configuracoes", "Home", null, new { @class = "btn btn-outline-primary col-md-12" })
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="tab-pane fade" id="logo" role="tabpanel" aria-labelledby="profile-tab">
        <form enctype="multipart/form-data" class="col-md-10 mx-auto row" action="~/Configuracoes/UploadLogo" method="post">
            <div class="form-group col-md-6 mx-auto">
                <h5 class=" p-1 mt-5">Envie a logo da empresa:</h5>
                <input type="file" name="logo" class="form-control-file p-3 border border-dark rounded mt-3 bg-light" />
            </div>

            <div class="col-md-12 m-auto p-5 d-flex justify-content-center">
                <div class="col-md-3">
                    <div class="row p-2">
                        <button type="submit" class="btn btn-success col-md-12">Salvar</button>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="row p-2">
                        @Html.ActionLink("Voltar", "Configuracoes", "Home", null, new { @class = "btn btn-outline-primary col-md-12" })
                    </div>
                </div>
            </div>

        </form>
    </div>

    <div class="tab-pane fade" id="icone" role="tabpanel" aria-labelledby="contact-tab">
        <form action="~/Configuracoes/ChangeIcons" method="post">
            <div class="row">

                <div class="col-md-3 m-4">
                    <label for="PRO" class="col-md-12 p-5 rounded border border-dark rounded bg-light">
                        <img class="samples" src="~/Content/img/pro_samples.png" alt="Beuty Ícons" />
                    </label>
                    Opção 1:
                    @if (icon == "PRO")
                    {
                        <input type="radio" name="icon" id="PRO" value="PRO" checked />
                    }
                    else
                    {
                        <input type="radio" name="icon" id="PRO" value="PRO" />
                    }
                </div>

                <div class="col-md-3 m-4">
                    <label for="CARTOON" class="col-md-12 p-5 border border-dark rounded bg-light">
                        <img class="samples" src="~/Content/img/cartoon_samples.png" alt="Beuty Ícons" />
                    </label>
                    Opção 2:

                    @if (icon == "CARTOON")
                    {
                        <input type="radio" name="icon" id="CARTOON" value="CARTOON" checked />
                    }
                    else
                    {
                        <input type="radio" name="icon" id="CARTOON" value="CARTOON" />
                    }
                </div>
            </div>

            <div class="row mt-4">
                <div class="col-md-6 m-auto">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="row p-2">
                                <button type="submit" class="btn btn-success col-md-12">Salvar</button>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="row p-2">
                                @Html.ActionLink("Voltar", "Configuracoes", "Home", null, new { @class = "btn btn-outline-primary col-md-12" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>